### ISSUE TITLE
Command Does Not Work

### ISSUE THREAD

**Issue by lrljoe** [michaelnabil230/laravel-block-ip#9]
Running the command:
```console
php artisan block-ip:block 252.2.2.2
```
Results in 

```The "ips" argument does not exist.```

**Comment by lrljoe** [comment]
So I've rewritten a few chunks of the SP, removed the dependency on Spatie Package Tools and adjusted the commands, and it now works smoothly.

I'll issue a PR in due course

**Comment by michaelnabil230** [comment]
Hello, @lrljoe,

To ensure you have the latest version of the package before running the `block-ip:block` command, you can add a `composer update` command before it. Here's the updated command sequence:

```bash
composer update michaelnabil230/laravel-block-ip
php artisan block-ip:block 127.0.0.1 127.0.0.2
```

The `composer update` command will update the `laravel-block-ip` package to the latest version, and then you can proceed with executing the `block-ip:block` command.

Please note that running `composer update` will update all packages in your Laravel project to their latest versions. If you only want to update the `laravel-block-ip` package, you can specify it in the command as shown above.

Thank you for using https://github.com/michaelnabil230/laravel-block-ip.

If you have any further questions or need additional assistance, please let me know.

**Comment by lrljoe** [comment]
I definitely pulled the latest version and still had the same issue.  I think it may be a CF issue depending on WAF approach, I'm trying to narrow it down, but presently have a working (adjusted) approach.
